"""add user role

Revision ID: 8eabed1c8237
Revises: 3318ef2bf36f
Create Date: 2024-03-27 15:53:59.029591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8eabed1c8237"
down_revision: Union[str, None] = "3318ef2bf36f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column(
        "users",
        sa.Column(
            "role", sa.Enum("admin", "moderator", "user", name="role"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
